# Generated by Django 3.1.7 on 2021-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0003_prime1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime1',
            name='prime_f',
            field=models.IntegerField(max_length=500),
        ),
    ]
