# Generated by Django 3.1.7 on 2021-03-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0004_auto_20210331_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime1',
            name='prime_f',
            field=models.CharField(max_length=500000000),
        ),
        migrations.AlterField(
            model_name='prime1',
            name='prime_s',
            field=models.CharField(max_length=500000000),
        ),
    ]
