# Generated by Django 3.1.7 on 2021-03-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0005_auto_20210331_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prime1',
        ),
        migrations.RemoveField(
            model_name='prime',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='prime',
            name='prime_f',
            field=models.CharField(max_length=500000000),
        ),
        migrations.AlterField(
            model_name='prime',
            name='prime_s',
            field=models.CharField(max_length=500000000),
        ),
    ]
